### ISSUE TITLE
Error help

### ISSUE THREAD

**Issue by spackletoe** [DJWoodZ/Satisfactory-Discord-Bot#37]
Any idea what this error is?  Trying to get my bot working since the 1.0 upgrade, I think I've  updated to all the new files, and I've rechecked my .env.local and I'm currently getting this.

<img width="999" alt="image" src="https://github.com/user-attachments/assets/926aab56-1db5-4ad3-808d-9c931ef80641">

Thanks,

-joe

**Comment by DJWoodZ** [comment]
Hi Joe,

That error suggests it is having trouble reading the log. Check the location of the log file is correct in your `.env.local`, and that the bot has permissions to read the log file, including its parent directories.

**Comment by spackletoe** [comment]
marking this as done.  Thanks again for your quick attention! It was indeed a mix or incorrect paths and permissions!
